### ISSUE TITLE
Reading data from sensors

### ISSUE THREAD

**Issue by narensankar0529** [qqaatw/LibJciHitachi#2]
Are the DH sensor data supported to be read only when the DH is powered on? i.e. state of the DH is actually running ON? When I read the pm2.5 sensor for example of the currently humidity sensor data doesn't seem to be updated when the DH is not currently being used in any mode

**Comment by qqaatw** [comment]
I'm not quite sure what you meant by **read only**. I think sensors are not supposed to be updated by users?

If you meant sensor data is not updated when the device is powered off, that would probably be correct as some devices might not be continuously monitoring sensor data when they're powered off. I'm not sure whether your device is the case.

**Comment by narensankar0529** [comment]
ok. Understood. Does your AirCon work this way? Basically the only way for example I can read the humidity sensor or the pm2.5 sensor is to set the DH to either air purifier mode or dehumidify mode and run it. So it is not possible to make an automation work here which checks the humidity and turns on the dehumidifier or check the pm2.5 sensor and turn on the air purifier. So only way to make automations work is to use external other sensors.

**Comment by narensankar0529** [comment]
So I guess this is specific to how the DH works then. Thanks
