### ISSUE TITLE
New API or changes?

### ISSUE THREAD

**Issue by narensankar0529** [qqaatw/LibJciHitachi#3]
With latest update of firmware and app and library getting error - 

Has the API changed or does the new firmware from Hitachi require some different mechanism to connect?

python3 example.py
Traceback (most recent call last):
  File "/Users/nsankar/Projects/LibJciHitachi/example.py", line 11, in <module>
    api.login()
  File "/Users/nsankar/Projects/LibJciHitachi/JciHitachi/api.py", line 384, in login
    self._peripherals = Peripheral.from_device_names(
  File "/Users/nsankar/Projects/LibJciHitachi/JciHitachi/api.py", line 95, in from_device_names
    assert device_names is None or len(device_names) == len(peripherals), \
AssertionError: Some of device_names are not available from the API.

more example.py
from JciHitachi.api import JciHitachiAPI

# Fill out your Jci Hitachi email address, password, and device name.

# Login
api = JciHitachiAPI(EMAIL, PASSWORD, DEVICENAME)
api.login()

# Check device status
device_status = api.get_status()
print(device_status[DEVICENAME].status)

**Comment by qqaatw** [comment]
Exactly, the new firmware is using a new API. I would probably release a new version in the next few days that fits with the new API. BTW you should not paste your credentials here, please remove it as soon as possible. Tks.

**Comment by qqaatw** [comment]
Would you mind inviting me to the home group again so that I can test out your device.

**Comment by narensankar0529** [comment]
You are still in the home group. For some reason after this firmware update the connection to the device has been flaky even from the official app. The device is reported as disconnected most of the time. Not sure if there is any issue on hitachi side

Thanks!
—————

Naren Sankar

**Comment by qqaatw** [comment]
It seemed that the firmware update this time also unbound all built in sub-services of the Hitachi app such as Google home and home group linking, so now I'm not in the home group (I saw I was kicked from the group yesterday).

**Comment by qqaatw** [comment]
Closing as the new version was released.
